### ISSUE TITLE
Publish APK on Github?

### ISSUE THREAD

**Issue by IzzySoft** [tairrzayev/bnotes#1]
Would you consider including the `.apk` file here at Github (e.g. in the `releases/`), so people without Play Store access can use it as well? Would be great, and thanks in advance!

**Comment by tairrzayev** [comment]
Hi,

Thank you for the issue! I am not sure that putting BLOBs into the repo is a good idea though. Moreover, [you can find many 'mirrors' on web](https://www.google.lv/search?q=budget+notes+apk), which are more or less in sync with the google play.

**Comment by IzzySoft** [comment]
@tairrzayev you don't necessarily need to place it inside the repository. But whenever you release a new version, you could mark that here as well (using tags) and attach the `.apk` file to the tag [here](https://github.com/tairrzayev/bnotes/releases). Many projects do it that way (and the `releases/` page is intended for blobs – for each tag, `.zip` and `.tar.gz` archives are even auto-generated).

And no, grabbing `.apk` files from "some search results on the web" is never a good idea. One never knows whether it's the original – or contains some (usually unwanted) "add-ons" (aka malware). Always better to get it directly from the dev, and know exactly where to find updates then (if you'd add it to `releases/`, that would then also be [here](https://android.izzysoft.de/repo) if that's OK with you :)

**Comment by tairrzayev** [comment]
> But whenever you release a new version, you could mark that here as well (using tags) and attach the .apk file to the tag here. Many projects do it that way (and the releases/ page is intended for blobs – for each tag, .zip and .tar.gz archives are even auto-generated).

I guess  [this](https://help.github.com/articles/creating-releases/) is what you mean. I was actually going to stick to that but I've never made any new release since publishing the source on github. I've made a couple of refactoring changes then, which require some testing. I'll have a check tomorrow & create release so you can have the apk.

> And no, grabbing .apk files from "some search results on the web" is never a good idea.

Can't argue with that - you are absolutely right :) Not that I can suggest any trustworthy Google Play "clones" myself either.

> (if you'd add it to releases/, that would then also be here if that's OK with you :)

No objections here.

Cheers & thank you for the input!

**Comment by IzzySoft** [comment]
> I guess [this](https://help.github.com/articles/creating-releases/) is what you mean.

Yupp, that would be a "full release" where you can attach additional files to – and yes, that's what I've meant.

> I'll have a check tomorrow & create release so you can have the apk.

That would be cool, thanks!

> Not that I can suggest any trustworthy Google Play "clones" myself either.

If you mean "apps to access PS": Well, there's [BlankStore](https://github.com/mar-v-in/BlankStore) (from the [microG](https://github.com/microg/) project), but it's quite limited (but nice; you can at least get all free apps and even update them, just doesn't work with payed apps). If you mean alternative markets: well, there's F-Droid. And with its client, you can access other compatible repositories (including [mine](https://android.izzysoft.de/repo), as mentioned – thanks for your agreement!). With the `.apk` always published here in the `releases/`, it would be automatically updated in my repo – and users could retrieve updates from there, and even be notified if there are any – even without any GApps or Playstore on their devices.

Thanks a lot for your help!

**Comment by tairrzayev** [comment]
[Here you go!](https://github.com/tairrzayev/bnotes/releases/tag/v1.15) My apologies for taking so long, was a bit busy.

**Comment by IzzySoft** [comment]
Thanks a lot! Just added it to the repo. If you make a new release, and add it here the same way, it should be updated in my repo within 24h automatically.

And no apologies needed, I know what "busy" means ;) You've been rather fast – I'm still waiting for responses on issues I've opened in March :)
